# Generated by Django 5.0.3 on 2024-03-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
